on:
  push: 
    branches:
      - main

env: 
  REGISTRY: ghcr.io
  SOURCE_IMAGE: ghcr.io/reasomatic/agents-docker-private:latest
  TARGET_IMAGE: ghcr.io/reasomatic/agents-docker:latest
  
jobs:
  pull-retag-push:      
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the Source Image
        run: |
          docker pull ${{ env.SOURCE_IMAGE }}

      - name: Retag and Push; In This Repository
        run: |
          docker tag ${{ env.SOURCE_IMAGE }} ${{ env.TARGET_IMAGE }}
          docker push ${{ env.TARGET_IMAGE }}
