on:
  push: 
    branches:
      - main

env: 
  IMAGE_SOURCE: ghcr.io/reasomatic/agents-docker-private/agents-docker:latest
  IMAGE_TARGET: ghcr.io/reasomatic/agents-docker/agents-docker:latest
  
jobs:
  pullimage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the Source Image
        run: |
          docker pull ${{ IMAGE_SOURCE }}

      - name: Build New Docker Image
        run: |
          echo -e "FROM ${{ IMAGE_SOURCE }}" > Dockerfile
          docker build -t ${{ IMAGE_TARGET }} .
  
      - name: Push New Docker Image Under This Repo
        run: |
          docker push ${{ IMAGE_TARGET }}
      
