on:
  push: 
    branches:
      - main

jobs:
  pullimage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pulling
        run: |
          docker pull ghcr.io/reasomatic/hello_docker:latest
          docker tag ghcr.io/reasomatic/hello_docker:latest ghcr.io/reasomatic/hello_docker:available
          docker push ghcr.io/reasomatic/hello_docker:available
