on:
  push: 
    branches:
      - main
      
jobs:
  pullimage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pulling 
        run: |
          docker image ls
          docker ps
          docker pull ghcr.io/reasomatic/hello_docker:available-v2
          docker image ls
          docker ps

      - name: Build New Docker Image
        run: |
          echo -e "FROM ghcr.io/reasomatic/hello_docker:available-v2\n\n# Your modifications here" > Dockerfile
          docker build -t ghcr.io/reasomatic/agents-docker/hello_docker:final .
          docker image ls
          docker ps
  
      - name: Push New Docker Image to Public Repository
        run: |
          docker push ghcr.io/reasomatic/agents-docker/hello_docker:final
          docker image ls
          docker ps
      
