on:
  push: 
    branches:
      - main
      
jobs:
  pullimage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pulling and running
        run: |
          docker image ls
          docker ps
          docker pull ghcr.io/reasomatic/hello_docker:available-v2
          docker image ls
          docker ps
      - name: Build New Docker Image
        run: |
          docker build -t new_image ghcr.io/reasomatic/hello_docker:available-v2
          docker image ls
          docker ps
          
      - name: push to public
        run: |
          docker push ghcr.io/reasomatic/agents-docker/hello_docker:latest
          docker image ls
          docker ps
      
